import { useState, type ChangeEvent, useEffect } from "react";

import styles from "./Login.module.css";
import { Link, useNavigate } from "react-router-dom";
import { emailRegex, passwordRegex } from "../../Utils/RegEx";
import toast from "react-hot-toast";
import axios from "axios";
import { API_BASE_URL } from "../../Utils/api";
import {
  GoogleLoginButton,
} from "react-social-login-buttons";

import { useGoogleLogin } from "@react-oauth/google";
import { IsloggedIn } from "../../Utils/Auth";

function Login() {
  const [userDetails, setuserDetails] = useState({
    password: "",
    email: "",
  });

  const [isloading, setisloading] = useState(false);

  const [show, setshow] = useState(false);

  const navigate = useNavigate();

  function handleInputChange(event: ChangeEvent<HTMLInputElement>): void {
    const { name, value } = event.target;
    // console.log(name, value);

    setuserDetails((prev) => ({
      ...prev,
      [name]: value,
    }));
  }


  useEffect(()=>{
    IsloggedIn() ? navigate("/home") : ""
  },[]) 

  const handleLogin = async () => {
    if (!emailRegex.test(userDetails.email)) {
      toast.error("Please enter a valid email address");
      return;
    }

    if (!passwordRegex.test(userDetails.password)) {
      toast.error(
        "Password must be at least 8 characters and must include at least one special character and one number"
      );
      return;
    }

    

    try {
      setisloading(true);
      const response = await axios.post(
        `${API_BASE_URL}/user/login`,
        userDetails
      );
      console.log(response);

      toast.success(response.data.message);

      localStorage.setItem("token", response.data.token);
      navigate("/home");
      setisloading(false);
    } catch (error: any) {
      toast.error(error.response.data.message);
      console.log(error);
      setisloading(false);
    }
  };

  const handleContinueWithGoogle = useGoogleLogin({
    onSuccess: async (response: any) => {
      console.log(response);

      const res = await axios.get(
        "https://www.googleapis.com/oauth2/v3/userinfo",
        {
          headers: { Authorization: `Bearer ${response.access_token}` },
        }
      );

      console.log(res.data);

      const newUser = {
        username: res.data.name,
        email: res.data.email,
        autoGenerated: true,
      };

      console.log(newUser);

      try {
        const response = await axios.post(
          `${API_BASE_URL}/user/login`,
          newUser
        );
        console.log(response);

        toast.success(response.data.message);

        localStorage.setItem("token", response.data.token);
        navigate("/home");
        setisloading(false);
      } catch (error: any) {
        toast.error(error.response.data.message);
        console.log(error);
        setisloading(false);
      }
    },
    onError: (error: any) => {
      setisloading(false);
      console.log(error);
    },
  });

  return (
    <div className={styles.container}>
      <div className={styles.formContainer}>
        <h2>Login...</h2>
        <div className={styles.social}>
          <div
            onClick={() => {
              setisloading(true);
              handleContinueWithGoogle();
            }}
          >
            <GoogleLoginButton>Continue with Google</GoogleLoginButton>
          </div>
        </div>
        <div className={styles.inputContainer}>
          <input
            value={userDetails.email}
            placeholder="Enter your email..."
            type="email"
            name="email"
            onChange={handleInputChange}
          />

          <div className={styles.passwordContainer}>
            <input
              value={userDetails.password}
              placeholder="Enter your password..."
              type={show ? "text" : "password"}
              name="password"
              onChange={handleInputChange}
            />
            <button
              onClick={() => {
                setshow(!show);
              }}
            >
              {show ? "HIDE" : "SHOW"}
            </button>
          </div>
          <button disabled={isloading} onClick={handleLogin}>
            {isloading ? "Loading..." : "LOGIN"}
          </button>
        </div>
        <div className={styles.footer}>
          <Link to="/signup">Don't have an account? Signup</Link>
          <Link to="/forgot-password">Forgot Password?</Link>
        </div>
      </div>
    </div>
  );
}

export default Login;
